## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module 

---
- hosts: localhost
  vars:
    ansible_python_interpreter: /bin/python3
    vcenter_hostname: "200.200.200.251"
    vcenter_username: "administrator@vsphere.kh"
    vcenter_password: "VMware1!"
    datacenter_name: "vSAN Datacenter"
##    esxi_hostname: "200.200.200.250"
##    student_ID: "S00"
    full_folder_prefix: "vSAN Datacenter/vm/Students/"
    datastore_name: "vsanDatastore"
    template_name: "Temp-Win2019"
    snapshot_src_name: "20220315"

  vars_prompt:
    - name: student_ID
      prompt: What is your student ID (ex:S00)?
      private: no

    - name: esxi_hostname
      prompt: What is your esxi_hostname (ex:200.200.200.250)?
      private: no


  tasks:
  - name: Deploy Domain Controller VM from Template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-DC' }}"
      state: "poweredon"
      datacenter: '{{ datacenter_name }}'
      folder: "{{ full_folder_prefix + student_ID }}"
      esxi_hostname: '{{ esxi_hostname }}'
      datastore: "{{ datastore_name }}"
      template: "{{ template_name }}"
      linked_clone: True
      snapshot_src: "{{ snapshot_src_name }}"
      networks:
      - name: "{{ student_ID + '-Mgmt' }}"
        connected: True
        start_connected: True
        ip: 10.10.1.2
        netmask: 255.255.255.0
        gateway: 10.10.1.1
        dns_servers: 200.200.200.245
        type: static
      customization:
        password: VMware1!
      wait_for_customization: yes
      wait_for_customization_timeout: 900
    delegate_to: localhost

  - name: shutdown VM to change network connection
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-DC' }}"
      state: "shutdownguest"
      state_change_timeout: 60
    delegate_to: localhost

  - name: Poweron DC VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      name: "{{ student_ID + '-DC' }}"
      state: "poweredon"
      state_change_timeout: 60
    delegate_to: localhost